version: "3.9"

services:
    app:
        container_name: golang_container
        environment:
            - POSTGRES_USER=${POSTGRES_USER}
            - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
            - POSTGRES_DB=${POSTGRES_DB}
            - DATABASE_HOST=${DATABASE_HOST}
            - DATABASE_PORT=${DATABASE_PORT}
            - TZ=${TIMEZONE}
        tty: true
        build: .
        ports:
            - "8080:8080"
        restart: on-failure
        volumes:
            - .:/app
        depends_on:
            - db

    db:
        image: postgres:15.1-alpine
        container_name: postgres_container
        environment:
            - POSTGRES_USER=${POSTGRES_USER}
            - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
            - POSTGRES_DB=${POSTGRES_DB}
            - DATABASE_HOST=${DATABASE_HOST}
            - TZ=${TIMEZONE}
            - PGTZ=${TIMEZONE}
        ports:
            - "5432:5432"
        volumes:
            - ./pg_data:/var/lib/postgresql/data
            - ./schema/000001_init.up.sql:/docker-entrypoint-initdb.d/000001_init.up.sql

volumes:
    pg_data:
